# Portfolio Configuration
# Edit this file to customize your portfolio content

personal:
  name: "Sam Korostov"
  title: "Electrical & Computer Engineering Student"
  education: "University of Washington Seattle"
  email: "samkoro@uw.edu"
  github: "github.com/samkorostov"
  linkedin: "linkedin.com/in/samkorostov"

about:
  greeting: "Hey there! I'm Sam Korostov"
  description: |
    I'm an Electrical & Computer Engineering student at the University of Washington Seattle,
    graduating in June 2026 with a 3.75 cumulative GPA (3.8 departmental).

    I'm passionate about cloud infrastructure, building scalable systems, machine learning, and
    computer architecture.

    Currently serving as Lead Teaching Assistant for CSE12X at the Paul G. Allen School of
    Computer Science & Engineering, where I mentor students and coordinate teaching teams.

experience:
  - title: "Lead Teaching Assistant - CSE12X"
    company: "Paul G. Allen School of Computer Science & Engineering"
    period: "September 2025 - Present"
    description:
      - "Managed quiz sections by developing materials, coordinating TAs, and facilitating communication with instructors"
      - "Ensured clear expectations and effective student learning across multiple sections"

  - title: "Software Development Engineering Intern"
    company: "Amazon Web Services (AWS)"
    period: "June 2025 - September 2025"
    description:
      - "Designed and implemented entity-level traffic throttling capabilities for a critical service handling 1B+ weekly transactions"
      - "Built a CI/CD pipeline to improve deployment safety and maintainability of traffic management configurations"
      - "Unlocked a 1000x increase in scalability compared to the legacy architecture"

  - title: "Teaching Assistant - CSE 12X"
    company: "Paul G. Allen School of Computer Science & Engineering"
    period: "September 2024 - June 2025"
    description:
      - "Led weekly sections of around 20 students in introductory Java programming"
      - "Clarified core software principles from algorithmic logic to object-oriented design"
      - "Enabled sections to consistently outperform the course average on exams"

projects:
  - name: "64-bit Pipelined ARM (LEGv8) CPU"
    description: "Designed and implemented a 5-stage, 64-bit pipelined processor based on ARM LEGv8 RISC architecture with hazard detection, data forwarding, and branch prediction"
    technologies: ["SystemVerilog", "ModelSim", "Computer Architecture"]
    period: "April 2025 - June 2025"

  - name: "Multilingual Transformer Translator"
    description: "Built a Transformer model for multilingual translation with multi-head self-attention, positional encoding, and subword tokenization"
    technologies: ["Python", "PyTorch", "HuggingFace", "NLP"]
    period: "April 2025"

  - name: "HarvardX Student-Certification Prediction"
    description: "Built full ML pipeline with feature engineering and XGBoost classifier, securing top-3 finish out of 200+ teams in course Kaggle competition"
    technologies: ["Python", "XGBoost", "Scikit-Learn", "Pandas"]
    period: "March 2025"

skills:
  languages:
    - "Java"
    - "Python"
    - "TypeScript"
    - "C/C++"

  ml_data_science:
    - "PyTorch"
    - "NumPy"
    - "XGBoost"
    - "SciPy"
    - "Scikit-Learn"
    - "Pandas"

  cloud_backend:
    - "Amazon Web Services (AWS)"
    - "AWS CDK"
    - "FastAPI"
    - "Node.js"
    - "Spring Boot"

  hardware:
    - "SystemVerilog"
    - "FPGA"
    - "Embedded Systems"

  interests:
    - "Machine Learning & AI"
    - "Computer Architecture"
    - "Scalable Systems"
    - "Cloud Infrastructure"
